project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: iFrame.qmd
        text: Questionnaire iFrame
      - href: Data.qmd
        text: Data Insights        
      - href: DashboardDemonstration.qmd
        text: Dashboard Demonstration
      - href: GrowthPotential.qmd
        text: Growth Potential
      
        
        
        
    logo: images/logo_tepak.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

